development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_development
  pool: 5 
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: blog_app_production
  pool: 5
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_test
  pool: 5
  timeout: 5000